// Writing rules for the CV and the portfolio copy.
// Plain punctuation, single spaces, and none of the stock phrases that make a CV read as machine written.

export const FORBIDDEN_CHARACTERS = [
  { char: ':', name: 'colon' },
  { char: ';', name: 'semicolon' },
  { char: '-', name: 'hyphen' },
  { char: '‒', name: 'figure dash' },
  { char: '–', name: 'en dash' },
  { char: '—', name: 'em dash' },
  { char: '−', name: 'minus sign' },
];

export const BANNED_PHRASES = [
  'leverage', 'leveraged', 'leveraging', 'spearhead', 'spearheaded', 'delve', 'robust',
  'seamless', 'seamlessly', 'cutting edge', 'passionate', 'dynamic', 'innovative',
  'streamline', 'streamlined', 'synergy', 'synergies', 'orchestrate', 'orchestrated',
  'orchestration', 'empower', 'empowered', 'transformative', 'pivotal', 'meticulous',
  'meticulously', 'tapestry', 'landscape', 'foster', 'fostered', 'harness', 'harnessed',
  'elevate', 'elevated', 'showcase', 'navigate', 'navigating', 'realm', 'holistic',
  'actionable', 'results driven', 'detail oriented', 'track record', 'utilize', 'utilized',
  'utilise', 'utilised', 'furthermore', 'moreover', 'additionally', "in today's",
  'fast paced', 'ever evolving', 'testament', 'underscore', 'underscores', 'embark',
  'intricate', 'nuanced', 'paramount', 'game changer', 'world class', 'best in class',
  'state of the art', 'supercharge', 'unlock', 'unleash', 'journey', 'thrive', 'vibrant',
  'crucial', 'comprehensive', 'deep dive', 'in conclusion', 'as an ai', 'generated by',
];

const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const PHRASE_PATTERNS = BANNED_PHRASES.map((p) => ({
  phrase: p,
  re: new RegExp(`(^|[^a-z])${escape(p)}([^a-z]|$)`, 'i'),
}));

/** Returns a list of human readable problems for one piece of text. Empty means it passes. */
export function findStyleProblems(text) {
  const problems = [];
  for (const { char, name } of FORBIDDEN_CHARACTERS) {
    if (text.includes(char)) problems.push(`contains a ${name}`);
  }
  if (/ {2,}/.test(text)) problems.push('contains a double space');
  if (text !== text.trim()) problems.push('starts or ends with a space');
  if (/\s[,.!?]/.test(text)) problems.push('has a space before punctuation');
  for (const { phrase, re } of PHRASE_PATTERNS) {
    if (re.test(text)) problems.push(`uses "${phrase}"`);
  }
  return problems;
}

/** Walks any JSON value and yields [path, string] pairs. */
export function* strings(value, path = '$') {
  if (typeof value === 'string') yield [path, value];
  else if (Array.isArray(value)) for (const [i, v] of value.entries()) yield* strings(v, `${path}[${i}]`);
  else if (value && typeof value === 'object') for (const [k, v] of Object.entries(value)) yield* strings(v, `${path}.${k}`);
}
